apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-config
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  networkid: "{{ .Values.geth.genesis.networkId }}"
  genesis.json: |-
    {
        "config": {
            "chainId": {{ .Values.geth.genesis.networkId }},
            "homesteadBlock": 0,
            "eip150Block": 0,
            "eip155Block": 0,
            "eip158Block": 0,
            "byzantiumBlock": 0,
            "constantinopleBlock": 0,
            "petersburgBlock": 0,
            "istanbulBlock": 0,
            "berlinBlock": 0,
            "clique": {
              "period": 5,
              "epoch": 30000
            }
        },
        "difficulty":  {{ .Values.geth.genesis.difficulty | quote }},
        "gasLimit": {{ .Values.geth.genesis.gasLimit | quote }},
        "extradata": "0x00000000000000000000000000000000000000000000000000000000000000007df9a875a174b3bc565e6424a0050ebc1b2d1d820000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "alloc": {
            {{- if .Values.geth.account.address }}
            {{ .Values.geth.account.address | quote }}: {
                "balance": "1000000000000000000000000"
            }
            {{- end }}
        }
    }
